language: bash

sudo: false

services:
  - docker

env:
  - Dockerfile=2
  - Dockerfile=1

before_script:
  - make image dockerfile=$Dockerfile tag=test
  - make deps.bats

script:
  - make test dockerfile=$Dockerfile tag=test

notifications:
  email:
    on_success: never
    on_failure: always
