language: bash

sudo: false

services:
  - docker

env:
  - Dockerfile=2
  - Dockerfile=1

before_script:
  - make image DOCKERFILE=$Dockerfile VERSION=test
  - make deps.bats

script:
  - make test DOCKERFILE=$Dockerfile VERSION=test

notifications:
  email:
    on_success: never
    on_failure: always
