<?php
$var = getopt('', ['version:', 'dockerfile:']);
$isPhpDocV1 = (reset(explode('/', $var['dockerfile'])) === '1');
$PhpDocVer = reset(explode('-', $var['version']));
?>
# AUTOMATICALLY GENERATED
# DO NOT EDIT THIS FILE DIRECTLY, USE /Dockerfile.tmpl.php

# https://hub.docker.com/_/php
<? if ($isPhpDocV1) { ?>
FROM php:5.6-alpine
<? } else { ?>
FROM php:7.4-alpine
<? } ?>

MAINTAINER Instrumentisto Team <developer@instrumentisto.com>


# Install phpDocumentor executable
<? if ($isPhpDocV1) { ?>
RUN pear install PhpDocumentor-<?= $PhpDocVer; ?> \
                 XML_Beautifier \
 && pear clear-cache \
 && rm -rf /tmp/*
<? } else { ?>
RUN curl -fL -o /usr/local/bin/phpdoc \
         https://github.com/phpDocumentor/phpDocumentor2/releases/download/v<?= $PhpDocVer; ?>/phpDocumentor.phar \
 && chmod 755 /usr/local/bin/phpdoc
<? } ?>
<? if ($isPhpDocV1) { ?>


# Tune up php.ini
RUN echo "error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED & ~E_WARNING" \
        > /usr/local/etc/php/conf.d/errors.ini

# Install required packages
RUN apk add --update --no-cache \
            make \
 && rm -rf /var/cache/apk/*
<? } ?>
<? if (!$isPhpDocV1) { ?>


# Install required PHP extensions and packages
RUN apk add --update --no-cache \
            graphviz \
            icu-libs libxslt libzip \
            make \
    \
 && apk add --no-cache --virtual .build-deps \
            icu-dev libxslt-dev libzip-dev \
 && docker-php-ext-install intl xsl zip \
    \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/*
<? } ?>


VOLUME ["/app"]

WORKDIR /app


ENTRYPOINT ["/usr/local/bin/phpdoc"]
